export const serverEnv = {
  // API Keys
  FE_SMCR_USERS_API_KEY: process.env.FE_SMCR_USERS_API_KEY,
  FE_SMCR_OCP_APIM_SUBSCRIPTION_KEY:
    process.env.FE_SMCR_OCP_APIM_SUBSCRIPTION_KEY,
  FE_SMCR_OCP_APIM_SUBSCRIPTION_KEY_UAT:
    process.env.FE_SMCR_OCP_APIM_SUBSCRIPTION_KEY_UAT,
  FE_SMCR_API_KEY_INSTITUTION: process.env.FE_SMCR_API_KEY_INSTITUTION,
  FE_SMCR_API_KEY_PROD_GET_USERS: process.env.FE_SMCR_API_KEY_PROD_GET_USERS,
  FE_SMCR_API_KEY_SERVICES: process.env.FE_SMCR_API_KEY_SERVICES,
  FE_SMCR_API_KEY_PNPG: process.env.FE_SMCR_API_KEY_PNPG,
  FE_SMCR_API_KEY_FIRMA_CON_IO: process.env.FE_SMCR_API_KEY_FIRMA_CON_IO,
  FE_SMCR_API_KEY_FIRMA_CON_IO_SIGNER_ID:
    process.env.FE_SMCR_API_KEY_FIRMA_CON_IO_SIGNER_ID,

  // Slack webhooks
  FE_SMCR_API_SLACK_REPORT_HOOK: process.env.FE_SMCR_API_SLACK_REPORT_HOOK,
  FE_SMCR_API_SLACK_CALL_MANAGEMENT_HOOK_TEST:
    process.env.FE_SMCR_API_SLACK_CALL_MANAGEMENT_HOOK_TEST,
  FE_SMCR_API_SLACK_CALL_MANAGEMENT_HOOK_PROD:
    process.env.FE_SMCR_API_SLACK_CALL_MANAGEMENT_HOOK_PROD,

  // Database
  DB_HOST: process.env.DB_HOST,
  DB_NAME: process.env.DB_NAME,
  DB_USER: process.env.DB_USER,
  DB_PASSWORD_B64: process.env.DB_PASSWORD_B64,
  DB_PORT: process.env.DB_PORT,
  DB_SSL: process.env.DB_SSL,

  // Onboarding paths
  UPLOAD: process.env.UPLOAD ?? "",
  ONBOARDING_BASE_PATH: process.env.ONBOARDING_BASE_PATH,
  ONBOARDING_BASE_PATH_UAT: process.env.ONBOARDING_BASE_PATH_UAT,
  GET_STATUS: process.env.GET_STATUS,
  GET_USERS_PATH: process.env.GET_USERS_PATH,
  GET_INSTITUTION: process.env.GET_INSTITUTION,
  GET_IPA: process.env.GET_IPA,
  GET_IPA_AOO: process.env.GET_IPA_AOO,
  GET_IPA_UO: process.env.GET_IPA_UO,
  GET_INFOCAMERE: process.env.GET_INFOCAMERE,

  // Azure Storage
  FE_SMCR_AZURE_STORAGE_CONNECTION_STRING:
    process.env.FE_SMCR_AZURE_STORAGE_CONNECTION_STRING,
  FE_SMCR_AZURE_STORAGE_CONTAINER:
    process.env.FE_SMCR_AZURE_STORAGE_CONTAINER ?? "config",
  FE_SMCR_AZURE_STORAGE_ONBOARDING_PRODUCTS_BLOB_PREFIX:
    process.env.FE_SMCR_AZURE_STORAGE_ONBOARDING_PRODUCTS_BLOB_PREFIX,

  // Portale Fatturazione
  STORAGE_TOKEN: process.env.STORAGE_TOKEN!,
  WEBHOOK_MANUAL_STORAGE: process.env.WEBHOOK_MANUAL_STORAGE!,

  // Logger
  FE_SMCR_LOGS_ENDPOINT: process.env.FE_SMCR_LOGS_ENDPOINT,
  FE_SMCR_LOG_LEVEL: process.env.FE_SMCR_LOG_LEVEL,

  // SMTP
  SMTP_HOST: process.env.SMTP_HOST,
  SMTP_PORT: process.env.SMTP_PORT,
  SMTP_USER: process.env.SMTP_USER,
  SMTP_PASS: process.env.SMTP_PASS,
} as const;

export const clientEnv = {
  NEXT_PUBLIC_MSAL_CLIENT_ID: process.env.NEXT_PUBLIC_MSAL_CLIENT_ID ?? "",
  NEXT_PUBLIC_MSAL_TENANT_ID: process.env.NEXT_PUBLIC_MSAL_TENANT_ID,
  NEXT_PUBLIC_MSAL_REDIRECT_URI: process.env.NEXT_PUBLIC_MSAL_REDIRECT_URI,
  NEXT_PUBLIC_APP_URL: process.env.NEXT_PUBLIC_APP_URL,
} as const;
