name: CD - Auth Function

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment where the artifact will be deployed.
        type: choice
        required: true
        default: "app-dev"
        options:
          - app-dev
          - app-prod
      use_staging_slot:
        description: True if artifact should be deployed to staging slot
        type: boolean
        required: false
        default: true
      use_private_agent:
        description: Use a private agent to deploy the built artifact.
        type: boolean
        required: false
        default: true
      use_labels:
        description: Use labels to start the right environment's GitHub runner. If use_labels is true, also use_private_agent must be set to true
        type: boolean
        required: false
        default: true

permissions:
  contents: read
  id-token: write

jobs:
  resolve-env:
    runs-on: ubuntu-latest
    outputs:
      resource_group_name: ${{ steps.set-vars.outputs.resource_group_name }}
      function_app_name: ${{ steps.set-vars.outputs.function_app_name }}
      runner_label: ${{ steps.set-vars.outputs.runner_label }}
    steps:
      - name: Set environment-specific variables
        id: set-vars
        run: |
          if [ "${{ inputs.environment }}" = "app-prod" ]; then
            echo "resource_group_name=plsm-p-itn-fn-rg-01" >> "$GITHUB_OUTPUT"
            echo "function_app_name=plsm-p-itn-auth-func-01" >> "$GITHUB_OUTPUT"
            echo "runner_label=prod" >> "$GITHUB_OUTPUT"
          else
            echo "resource_group_name=plsm-d-itn-apps-rg-01" >> "$GITHUB_OUTPUT"
            echo "function_app_name=plsm-d-itn-auth-func-01" >> "$GITHUB_OUTPUT"
            echo "runner_label=dev" >> "$GITHUB_OUTPUT"
          fi

  deploy:
    needs: resolve-env
    if: github.event_name == 'workflow_dispatch'
    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@main
    with:
      workspace_name: sm-auth-fn
      environment: ${{ inputs.environment }}
      resource_group_name: ${{ needs.resolve-env.outputs.resource_group_name }}
      function_app_name: ${{ needs.resolve-env.outputs.function_app_name }}
      use_staging_slot: ${{ inputs.use_staging_slot }}
      use_private_agent: ${{ inputs.use_private_agent }}
      use_labels: ${{ inputs.use_labels }}
      override_labels: ${{ needs.resolve-env.outputs.runner_label }}
    secrets: inherit
