name: Deploy Function App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: pagopa/dx/.github/workflows/release-azure-appsvc-v1.yaml@main
    with:
      workspace_name: "sm-certification-fn"
      environment: "prod"
      app_name: "sm-p-itn-plsm-cert-func-01"
      resource_group: "sm-p-itn-common-rg-01"
      disable_auto_staging_deploy: true
    secrets: inherit
