name: Infra Plan

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    paths:
      - "infra/resources/prod/**"
      - "infra/resources/_modules/**"
      - "infra/resources/environments/**"
      - ".github/workflows/infra_plan.yaml"
      - ".github/workflows/infra_apply.yaml"

permissions:
  contents: read
  id-token: write
  pull-requests: write

jobs:
  plan_prod:
    uses: pagopa/dx/.github/workflows/infra_plan.yaml@main
    name: Plan Infrastructure - Production
    secrets: inherit
    with:
      environment: prod
      base_path: infra/resources
      use_private_agent: true
      override_github_environment: app-prod
      env_vars: |
        TF_VAR_subscription_id=${{ vars.TF_VAR_SUBSCRIPTION_ID }}
        TF_VAR_eventhub_subscription_id=${{ vars.TF_VAR_EVENTHUB_SUBSCRIPTION_ID }}
        TF_VAR_container_pf=${{ vars.TF_VAR_CONTAINER_PF }}
        TF_VAR_bsmcr_principal_id=${{ vars.TF_VAR_BSMCR_PRINCIPAL_ID }}
        TF_VAR_storage_account_fatppublic_id=${{ vars.TF_VAR_STORAGE_ACCOUNT_FATPPUBLIC_ID }}
