name: Deploy Onboarding Function

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment where the artifact will be deployed.
        type: string
        required: true
        default: "app-prod"
      resource_group_name:
        description: "Function App resource group name"
        type: string
        required: true
        default: "plsm-p-itn-fn-rg-01"
      function_app_name:
        description: "Function App name"
        type: string
        required: true
        default: "plsm-p-itn-onboarding-func-01"
      use_staging_slot:
        description: True if artifact should be deployed to staging slot
        type: boolean
        required: false
        default: true
      use_private_agent:
        description: Use a private agent to deploy the built artifact.
        type: boolean
        required: false
        default: true
      use_labels:
        description: Use labels to start the right environment's GitHub runner. If use_labels is true, also use_private_agent must be set to true
        type: boolean
        required: false
        default: false
      override_labels:
        description: Needed for special cases where the environment alone is not sufficient as a distinguishing label
        type: string
        required: false
        default: ""

permissions:
  contents: read
  id-token: write

jobs:
  pre-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Enable Corepack & set Yarn version
        run: |
          corepack enable
          corepack prepare yarn@4.10.3 --activate

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate Avro types
        run: yarn workspace sm-onboarding-fn generate:avro

      - name: Commit generated files
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add apps/sm-onboarding-fn/generated/
          git diff --staged --quiet || git commit -m "chore: generate avro types [skip ci]"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

  deploy:
    needs: pre-build
    if: github.event_name == 'workflow_dispatch'
    uses: pagopa/dx/.github/workflows/function_app_deploy.yaml@main
    with:
      workspace_name: sm-onboarding-fn
      environment: ${{ inputs.environment }}
      resource_group_name: ${{ inputs.resource_group_name }}
      function_app_name: ${{ inputs.function_app_name }}
      use_staging_slot: ${{ inputs.use_staging_slot }}
      use_private_agent: ${{ inputs.use_private_agent }}
      use_labels: ${{ inputs.use_labels }}
      override_labels: ${{ inputs.override_labels }}
    secrets: inherit